name: RS_D2
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=1_gnu
  - ca-certificates=2022.3.18=h06a4308_0
  - certifi=2021.10.8=py38h06a4308_2
  - cudatoolkit=11.3.1=h2bc3f7f_2
  - ld_impl_linux-64=2.35.1=h7274673_9
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.3.0=h5101ec6_17
  - libgomp=9.3.0=h5101ec6_17
  - libstdcxx-ng=9.3.0=hd4cf53a_17
  - ncurses=6.3=h7f8727e_2
  - openssl=1.1.1n=h7f8727e_0
  - pip=21.2.4=py38h06a4308_0
  - python=3.8.12=h12debd9_0
  - readline=8.1.2=h7f8727e_1
  - setuptools=58.0.4=py38h06a4308_0
  - sqlite=3.38.0=hc218d9a_0
  - tk=8.6.11=h1ccaba5_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7f8727e_4
  - pip:
    - absl-py==1.0.0
    - antlr4-python3-runtime==4.8
    - appdirs==1.4.4
    - black==21.4b2
    - cachetools==5.0.0
    - charset-normalizer==2.0.12
    - click==8.0.4
    - cloudpickle==2.0.0
    - cycler==0.11.0
    - detectron2==0.6+cu111
    - fonttools==4.31.2
    - future==0.18.2
    - fvcore==0.1.5.post20220305
    - google-auth==2.6.2
    - google-auth-oauthlib==0.4.6
    - grpcio==1.44.0
    - hydra-core==1.1.1
    - idna==3.3
    - importlib-metadata==4.11.3
    - importlib-resources==5.6.0
    - iopath==0.1.9
    - kiwisolver==1.4.1
    - markdown==3.3.6
    - matplotlib==3.5.1
    - mypy-extensions==0.4.3
    - numpy==1.22.3
    - oauthlib==3.2.0
    - omegaconf==2.1.1
    - opencv-python==4.5.5.64
    - packaging==21.3
    - pandas==1.4.1
    - pathspec==0.9.0
    - pillow==9.0.1
    - portalocker==2.4.0
    - protobuf==3.19.4
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycocotools==2.0.4
    - pydot==1.4.2
    - pyparsing==3.0.7
    - python-dateutil==2.8.2
    - pytz==2022.1
    - pyyaml==5.1
    - regex==2022.3.15
    - requests==2.27.1
    - requests-oauthlib==1.3.1
    - rsa==4.8
    - six==1.16.0
    - tabulate==0.8.9
    - tensorboard==2.8.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - termcolor==1.1.0
    - toml==0.10.2
    - torch==1.9.0+cu111
    - torch-tb-profiler==0.4.0
    - torchaudio==0.9.0
    - torchvision==0.10.0+cu111
    - tqdm==4.63.1
    - typing-extensions==4.1.1
    - urllib3==1.26.9
    - werkzeug==2.0.3
    - yacs==0.1.8
    - zipp==3.7.0
prefix: /home/ubuntu/miniconda3/envs/RS_D2
